// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7fkpLWB5cRf0JZh0Q7bCbNNw57sZWgw',
    appId: '1:827592890672:web:89dbee60171af3ec5610f5',
    messagingSenderId: '827592890672',
    projectId: 'barber-shop-b5e54',
    authDomain: 'barber-shop-b5e54.firebaseapp.com',
    storageBucket: 'barber-shop-b5e54.firebasestorage.app',
    measurementId: 'G-2GHJQTLCLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SC0qjvk-8nUl_-S6Bwly3V_JI3kt43w',
    appId: '1:827592890672:android:0e0e4da570e25cb25610f5',
    messagingSenderId: '827592890672',
    projectId: 'barber-shop-b5e54',
    storageBucket: 'barber-shop-b5e54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHiM44n7jdjiTN6-ph61NGeh0oNimSt1o',
    appId: '1:827592890672:ios:558e49d0ac4485935610f5',
    messagingSenderId: '827592890672',
    projectId: 'barber-shop-b5e54',
    storageBucket: 'barber-shop-b5e54.firebasestorage.app',
    iosBundleId: 'com.example.elHou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHiM44n7jdjiTN6-ph61NGeh0oNimSt1o',
    appId: '1:827592890672:ios:558e49d0ac4485935610f5',
    messagingSenderId: '827592890672',
    projectId: 'barber-shop-b5e54',
    storageBucket: 'barber-shop-b5e54.firebasestorage.app',
    iosBundleId: 'com.example.elHou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI7fkpLWB5cRf0JZh0Q7bCbNNw57sZWgw',
    appId: '1:827592890672:web:e7131d30535293db5610f5',
    messagingSenderId: '827592890672',
    projectId: 'barber-shop-b5e54',
    authDomain: 'barber-shop-b5e54.firebaseapp.com',
    storageBucket: 'barber-shop-b5e54.firebasestorage.app',
    measurementId: 'G-YNL6GG06FR',
  );
}
